[project]
name = "stackclient"
version = "0.2.3"
description = "Python library to interact with Stackspot Agents API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "urllib3>=2.5.0",
]
